# Generated by Django 3.2.5 on 2024-05-25 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ak_admin', '0005_investor_base_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_name', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_no', models.CharField(blank=True, max_length=256, null=True)),
                ('expense_amount', models.PositiveIntegerField(default=0)),
                ('expense_image', models.ImageField(blank=True, null=True, upload_to='expense/')),
                ('notes', models.TextField(blank=True, null=True)),
                ('expense_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.expensetype')),
                ('vehicle_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ak_admin.vehicle')),
            ],
        ),
    ]
