# Generated by Django 5.0.6 on 2024-07-02 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CarModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand_name", models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name="Investor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("investor_name", models.CharField(max_length=256)),
                ("investment_amount", models.IntegerField(default=0)),
                ("base_amount", models.IntegerField(default=0)),
                (
                    "investor_pic",
                    models.ImageField(blank=True, null=True, upload_to="investor/"),
                ),
                ("investment_date", models.DateField(blank=True, null=True)),
                ("returned_amount", models.PositiveIntegerField(default=0)),
                ("return_date", models.DateField(blank=True, null=True)),
                ("remarks", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_name", models.CharField(max_length=258)),
                (
                    "vehicle_pic",
                    models.ImageField(blank=True, null=True, upload_to="vehicle/"),
                ),
                (
                    "pic2",
                    models.ImageField(blank=True, null=True, upload_to="vehicle/"),
                ),
                (
                    "pic3",
                    models.ImageField(blank=True, null=True, upload_to="vehicle/"),
                ),
                ("purchase_date", models.DateField(blank=True, null=True)),
                ("purchase_from", models.CharField(max_length=258)),
                ("base_amount", models.PositiveIntegerField(default=0)),
                ("total_amount", models.PositiveIntegerField(default=0)),
                ("vehicle_type", models.CharField(max_length=258)),
                ("maintenance_cost", models.PositiveIntegerField(default=0)),
                ("status", models.CharField(blank=True, max_length=250, null=True)),
                ("rto_status", models.BooleanField(default=False)),
                (
                    "sold_amount",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("sold_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "brand_name",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ak_admin.carmodel",
                    ),
                ),
                (
                    "investor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ak_admin.investor",
                    ),
                ),
            ],
        ),
    ]
