# Generated by Django 4.2 on 2024-05-16 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investor_name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.CharField(max_length=258)),
                ('vehicle_type', models.CharField(max_length=258)),
                ('model_name', models.CharField(max_length=258)),
                ('purchase_from', models.CharField(max_length=258)),
                ('amount', models.CharField(max_length=250)),
                ('maintenance_cost', models.PositiveIntegerField(default=1)),
                ('notes', models.TextField()),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ak_admin.investor')),
            ],
        ),
    ]
