# Generated by Django 3.2 on 2024-05-25 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investor_name', models.CharField(max_length=256)),
                ('investment_amount', models.CharField(blank=True, max_length=256, null=True)),
                ('investor_pic', models.ImageField(blank=True, null=True, upload_to='investor/')),
                ('investment_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=258)),
                ('vehicle_pic', models.ImageField(blank=True, null=True, upload_to='vehicle/')),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_from', models.CharField(max_length=258)),
                ('base_amount', models.CharField(max_length=250)),
                ('vehicle_type', models.CharField(max_length=258)),
                ('maintenance_cost', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(blank=True, max_length=250, null=True)),
                ('rto_status', models.BooleanField(default=False)),
                ('sold_amount', models.CharField(blank=True, max_length=250, null=True)),
                ('sold_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField()),
                ('brand_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ak_admin.carmodel')),
                ('investor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ak_admin.investor')),
            ],
        ),
    ]
