# Generated by Django 3.2.5 on 2024-05-25 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ak_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
