# Generated by Django 5.0.6 on 2024-07-13 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ak_admin", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="vehicle_no",
            field=models.CharField(blank=True, max_length=258, null=True),
        ),
        migrations.CreateModel(
            name="Entry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("notes", models.TextField()),
                ("amount", models.IntegerField()),
                (
                    "investor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ak_admin.investor",
                    ),
                ),
            ],
        ),
    ]
