# Generated by Django 4.2 on 2024-05-16 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ak_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='purchase_date',
            field=models.DateField(),
        ),
    ]
