# Generated by Django 3.2.5 on 2024-05-25 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ak_admin', '0002_alter_vehicle_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='pic2',
            field=models.ImageField(blank=True, null=True, upload_to='vehicle/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='pic3',
            field=models.ImageField(blank=True, null=True, upload_to='vehicle/'),
        ),
    ]
