# Generated by Django 4.2 on 2024-05-16 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ak_admin', '0002_alter_vehicle_purchase_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='maintenance_cost',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
