# Generated by Django 4.2 on 2024-05-16 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ak_admin', '0003_alter_vehicle_maintenance_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='investor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ak_admin.investor'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ak_admin.carmodel'),
        ),
    ]
