# Generated by Django 3.2.5 on 2024-05-25 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ak_admin', '0003_auto_20240525_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='total_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='investor',
            name='investment_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='base_amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
