# Generated by Django 3.2.5 on 2024-05-25 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ak_admin', '0004_auto_20240525_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='base_amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
