# Generated by Django 3.2.5 on 2024-05-25 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ak_admin', '0005_investor_base_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investor',
            name='base_amount',
        ),
        migrations.AlterField(
            model_name='investor',
            name='investment_amount',
            field=models.IntegerField(default=0),
        ),
    ]
