# Generated by Django 4.2 on 2024-06-11 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ak_admin', '0008_investor_return_date_investor_returned_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='base_amount',
            field=models.IntegerField(default=0),
        ),
    ]
